const authPage = document.getElementById("[Getting Started](/docs)

# OAuth 2.0

A complete guide to implementing Login and Sign Up using Deriv's OAuth 2.0 Authorization Code flow with PKCE.

## How the flow works

1

Generate PKCE

2

Redirect to Deriv

3

User Authenticates

4

Exchange Code

5

Use Token

1. **Generate PKCE** — Create a `code_verifier` (random string) and derive `code_challenge` = BASE64URL(SHA256(code_verifier)). Also generate a random `state` for CSRF protection.
2. **Redirect to Deriv** — Send the user to Deriv's authorization URL with all required parameters.
3. **User authenticates** — Deriv shows either the login or registration form. All login and consent screens are managed by the OAuth provider.
4. **Redirect back** — Deriv redirects the user to your `redirect_uri` with an authorization `code` and `state` .
5. **Verify state** — Confirm the returned `state` matches what you stored. This prevents CSRF attacks.
6. **Exchange code for token** — Your backend sends the `code` + `code_verifier` to Deriv's token endpoint and receives an `access_token` .
7. **Use the token** — Make authenticated API calls using the Bearer token.

## Before you start

You need:

- A registered OAuth2 client from Deriv with a `client_id` and a pre-registered `redirect_uri` .
- HTTPS enabled on your redirect URL.
- Your app must handle redirects, read the authorization code, and exchange it for tokens.

## Step 1: Generate PKCE parameters

##### What is PKCE?

**PKCE** (Proof Key for Code Exchange, pronounced “pixy”) prevents authorization code interception attacks. Even if an attacker intercepts the authorization code, they cannot exchange it without the original `code_verifier` that only your app generated and stored.

| Term | What it is |
| --- | --- |
| `code_verifier` | A cryptographically random string (43–128 characters) generated by your app |
| `code_challenge` | `BASE64URL(SHA256(code_verifier))` — sent with the authorization request |
| `code_challenge_method` | Always S256 (SHA-256) |

**Why it works:** Only the app that generated the `code_verifier` can complete the token exchange.

### Generating PKCE in JavaScript

```javascript
// 1. Generate a random code_verifier
const array = crypto.getRandomValues(new Uint8Array(64));
const codeVerifier = Array.from(array)
  .map(v => 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~'[v % 66])
  .join('');

// 2. Derive the code_challenge
const hash = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(codeVerifier));
const codeChallenge = btoa(String.fromCharCode(...new Uint8Array(hash)))
  .replace(/\+/g, '-')
  .replace(/\//g, '_')
  .replace(/=+$/, '');

// 3. Generate a random state for CSRF protection
const state = crypto.getRandomValues(new Uint8Array(16))
  .reduce((s, b) => s + b.toString(16).padStart(2, '0'), '');

// 4. Store code_verifier and state before redirecting
sessionStorage.setItem('pkce_code_verifier', codeVerifier);
sessionStorage.setItem('oauth_state', state);
```

Required authorization request parameters:

- response_type=code
- client_id
- redirect_uri
- scope
- state
- code_challenge + code_challenge_method=S256 (PKCE)

##### Storage tip

Store the `code_verifier` and `state` in `sessionStorage` before redirecting — they survive the redirect and are automatically cleared when the tab is closed. Clear them from storage immediately after a successful token exchange.

## Step 2: Redirect the user to the authorization endpoint

Send users to Deriv's OAuth 2.0 authorization endpoint:

```bash
https://auth.deriv.com/oauth2/auth
```

### Login

Login uses the standard OAuth2 + PKCE parameters with no additions.

#### Parameters

| Parameter | Value | Description |
| --- | --- | --- |
| `response_type` Required | `code` | Request an authorization code |
| `client_id` Required | `Your app ID` | Registered OAuth2 application ID from Deriv |
| `redirect_uri` Required | `Your callback URL` | Must exactly match the URI registered with Deriv |
| `scope` Required | `trade account_manage` | Requested permissions |
| `state` Required | `Random string` | CSRF protection — generate a new value for each request |
| `code_challenge` Required | `BASE64URL(SHA256(verifier))` | The PKCE challenge derived from code_verifier |
| `code_challenge_method` Required | `S256` | Always SHA-256 |
| `app_id` Optional | `Your legacy app ID` | Your V1 app ID from the Legacy Deriv API — include this only if you also maintain a legacy API app |

#### Login URL

```bash
https://auth.deriv.com/oauth2/auth?
  response_type=code
  &client_id={YOUR_CLIENT_ID}          # e.g. app12345
  &redirect_uri={YOUR_REDIRECT_URI}    # e.g. https://yourapp.com/callback
  &scope=trade+account_manage
  &state={RANDOM_STATE}                # e.g. abc123random
  &code_challenge={PKCE_CHALLENGE}     # e.g. E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM
  &code_challenge_method=S256
```

##### Also maintaining a Legacy API app?

If you also have an app on the Legacy Deriv API, append `&app_id=YOUR_LEGACY_APP_ID` to the login URL (and sign up URL). Deriv will check whether the user belongs to the old or new platform and route them to the appropriate version of your app.

#### Login URL with legacy app support

```bash
https://auth.deriv.com/oauth2/auth?
  response_type=code
  &client_id={YOUR_CLIENT_ID}
  &redirect_uri={YOUR_REDIRECT_URI}
  &scope=trade+account_manage
  &state={RANDOM_STATE}
  &code_challenge={PKCE_CHALLENGE}
  &code_challenge_method=S256
  &app_id={YOUR_LEGACY_APP_ID}      # V1 app ID from legacy-api.deriv.com
```

### Sign Up

Sign up uses the same base URL and parameters as login, plus one additional required parameter:

#### Required sign up parameter

| Parameter | Value | Description |
| --- | --- | --- |
| `prompt` Required | `registration` | Always this exact value. Tells Deriv to show the signup form instead of login. |

#### Optional partner attribution parameters

The following parameters are all optional and managed in the Partners dashboard. Include them to attribute signups to your partner account. The tracking token parameter has four equivalent names ( `t` , `affiliate_token` , `sidi` , `ca` ) — use whichever one appears in your referral link or Partners dashboard.

| Parameter | Value | Purpose |
| --- | --- | --- |
| `t` `affiliate_token` `sidi` `ca` | Your affiliate tracking token | Tracking and attribution. Use **only one** of these parameter names — they are equivalent aliases. Pick the one that appears in your referral link or in the Partners dashboard. |
| `utm_campaign` | Your campaign name | Identifies the marketing campaign |
| `utm_medium` | affiliate | Indicates a partner integration |
| `utm_source` | Your affiliate ID | Commission tracking and reporting |

##### Which tracking parameter should I use?

`t` , `affiliate_token` , `sidi` , and `ca` all serve the same purpose. Use the one that appears in your Deriv referral link or in your Partners dashboard — don't include more than one.

#### Sign Up URL

```bash
https://auth.deriv.com/oauth2/auth?
  response_type=code
  &client_id={YOUR_CLIENT_ID}          # e.g. app12345
  &redirect_uri={YOUR_REDIRECT_URI}    # e.g. https://yourapp.com/callback
  &scope=trade+account_manage
  &state={RANDOM_STATE}                # e.g. abc123random
  &code_challenge={PKCE_CHALLENGE}     # e.g. E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM
  &code_challenge_method=S256
  &prompt=registration
  &t={YOUR_TRACKING_TOKEN}             # or: affiliate_token | sidi | ca — use the name from your referral link
  &utm_campaign={YOUR_CAMPAIGN}        # e.g. dynamicworks
  &utm_medium=affiliate
  &utm_source={YOUR_AFFILIATE_ID}      # e.g. CU303219
```

##### Important

Always validate the `state` parameter on return and generate your `code_challenge` from a secure random `code_verifier` . Never reuse these values between requests.

## Step 3: Handle the callback

Whether the user logged in or signed up, the callback works exactly the same way. After authentication, Deriv redirects to your `redirect_uri` :

```bash
https://yourapp.com/callback?code=AUTHORIZATION_CODE&state=RANDOM_STATE
```

If something went wrong:

```bash
https://yourapp.com/callback?error=access_denied&error_description=User+cancelled
```

### Your app must:

1. **Verify the state** — compare the `state` from the URL with the value you stored before the redirect. If they don't match, abort — it may be a CSRF attack.
2. **Extract the code** — read the `code` query parameter.

##### The authorization code is single-use and expires quickly

Exchange it immediately. Do not store or log authorization codes.

## Step 4: Exchange code for tokens

Make a POST request from your **backend** to the token endpoint. Never perform the token exchange from the browser.

```http
POST https://auth.deriv.com/oauth2/token
```

### Request body (form-encoded)

```bash
grant_type=authorization_code
client_id=YOUR_CLIENT_ID
code=AUTH_CODE_FROM_CALLBACK
code_verifier=YOUR_ORIGINAL_CODE_VERIFIER
redirect_uri=https://your-app.com/callback
```

### cURL example

```bash
curl -X POST https://auth.deriv.com/oauth2/token \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "grant_type=authorization_code" \
  -d "client_id=YOUR_CLIENT_ID" \
  -d "code=AUTH_CODE" \
  -d "code_verifier=YOUR_CODE_VERIFIER" \
  -d "redirect_uri=https://your-app.com/callback"
```

### Token response

```json
{
  "access_token": "ory_at_...",
  "expires_in": 3600,
  "token_type": "Bearer"
}
```

## Step 5: Use the access token in API calls

Include the access token as a Bearer token in the `Authorization` header for all API calls:

```http
Authorization: Bearer YOUR_ACCESS_TOKEN
```

### Example

```bash
curl -X GET "https://api.derivws.com/trading/v1/options/accounts" \
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
```

## Quick reference

| Endpoint | URL |
| --- | --- |
| Authorization | `https://auth.deriv.com/oauth2/auth` |
| Token exchange | `https://auth.deriv.com/oauth2/token` |
| API base URL | `https://api.derivws.com` |

Where to find your values:

| Value | Where |
| --- | --- |
| `client_id` | Register an OAuth2 app with Deriv — you'll receive an app ID |
| `redirect_uri` | Set during app registration — must match exactly |
| `t / affiliate_token / sidi / ca (signup)` | Your referral link or the Partners dashboard — use the exact parameter name shown there |
| `utm_source / affiliate ID (signup)` | Managed and set in the Partners dashboard |
| `utm_campaign (signup)` | Managed and set in the Partners dashboard |
| `app_id (legacy)` | Your V1 app ID from legacy-api.deriv.com — only needed if you maintain a Legacy API app |

## Troubleshooting

| Problem | Likely cause | Fix |
| --- | --- | --- |
| State mismatch error | state in the callback doesn't match stored value | Store state in sessionStorage before redirecting, and don't regenerate it on page load |
| invalid_grant on token exchange | code_verifier doesn't match the challenge, or code expired/already used | Send the original code_verifier, not a newly generated one; exchange the code immediately |
| Redirect URI mismatch | URL doesn't exactly match what's registered | Check for trailing slashes, http vs https, port numbers |
| invalid_client | Wrong client_id | Verify your credentials from the Deriv dashboard |
| Login form shows instead of signup | Missing prompt=registration | Add prompt=registration to the authorization URL |
| Signup not tracked to partner | Missing or wrong UTM parameters | Verify your tracking token parameter (one of t, affiliate_token, sidi, or ca) matches the one shown in your referral link, and that utm_source, utm_medium, and utm_campaign are all present and correct |

## Implementation checklist

### Login

- `response_type` is `code`
- `client_id` and `redirect_uri` are registered with Deriv
- `code_challenge` and `state` are generated fresh for each request
- `code_verifier` is stored in `sessionStorage` before redirect
- Callback verifies `state` before exchanging the code
- Token exchange happens server-side (not in the browser)
- `code_verifier` is cleared from storage after use
- If maintaining a legacy app, `app_id` is set to your Legacy app ID (optional)

### Sign Up (additional)

- `prompt` is set to `registration` (required)
- Tracking token (one of `t` , `affiliate_token` , `sidi` , `ca` ), `utm_source` , `utm_campaign` , and `utm_medium` are set if needed — use the parameter name shown in your referral link or Partners dashboard (optional)");
const dashboardPage = document.getElementBy deriv app-Id 33p7PVqGTbhzPMv1GNtXr("Authorization token >pat_df0cbb0150b40589d016c49888fea3098f54ef3d5dde910f8e0ac4ef9f9fb0f5");account/client_id=019e4f44-45be-78e1-a2a7-808ded270fdd<>Redirect url=https://alphones142775-cmyk.github.io/Trading-platform/

function showLogin(){
  document.getElementById("loginForm").style.display = "block";
  document.getElementById("signupForm").style.display = "none";
}

function showSignup(){
  document.getElementById("loginForm").style.display = "none";
  document.getElementById("signupForm").style.display = "block";
}

function openDashboard(){

  authPage.style.display = "Anemiaton";
  dashboardPage.style.display = "block";
  OAuth 2.0 =[Getting Started](/docs)

# OAuth 2.0

A complete guide to implementing Login and Sign Up using Deriv's OAuth 2.0 Authorization Code flow with PKCE.

## How the flow works

1

Generate PKCE

2

Redirect to Deriv

3

User Authenticates

4

Exchange Code

5

Use Token

1. **Generate PKCE** — Create a `code_verifier` (random string) and derive `code_challenge` = BASE64URL(SHA256(code_verifier)). Also generate a random `state` for CSRF protection.
2. **Redirect to Deriv** — Send the user to Deriv's authorization URL with all required parameters.
3. **User authenticates** — Deriv shows either the login or registration form. All login and consent screens are managed by the OAuth provider.
4. **Redirect back** — Deriv redirects the user to your `redirect_uri` with an authorization `code` and `state` .
5. **Verify state** — Confirm the returned `state` matches what you stored. This prevents CSRF attacks.
6. **Exchange code for token** — Your backend sends the `code` + `code_verifier` to Deriv's token endpoint and receives an `access_token` .
7. **Use the token** — Make authenticated API calls using the Bearer token.

## Before you start

You need:

- A registered OAuth2 client from Deriv with a `client_id` and a pre-registered `redirect_uri` .
- HTTPS enabled on your redirect URL.
- Your app must handle redirects, read the authorization code, and exchange it for tokens.

## Step 1: Generate PKCE parameters

##### What is PKCE?

**PKCE** (Proof Key for Code Exchange, pronounced “pixy”) prevents authorization code interception attacks. Even if an attacker intercepts the authorization code, they cannot exchange it without the original `code_verifier` that only your app generated and stored.

| Term | What it is |
| --- | --- |
| `code_verifier` | A cryptographically random string (43–128 characters) generated by your app |
| `code_challenge` | `BASE64URL(SHA256(code_verifier))` — sent with the authorization request |
| `code_challenge_method` | Always S256 (SHA-256) |

**Why it works:** Only the app that generated the `code_verifier` can complete the token exchange.

### Generating PKCE in JavaScript

```javascript
// 1. Generate a random code_verifier
const array = crypto.getRandomValues(new Uint8Array(64));
const codeVerifier = Array.from(array)
  .map(v => 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~'[v % 66])
  .join('');

// 2. Derive the code_challenge
const hash = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(codeVerifier));
const codeChallenge = btoa(String.fromCharCode(...new Uint8Array(hash)))
  .replace(/\+/g, '-')
  .replace(/\//g, '_')
  .replace(/=+$/, '');

// 3. Generate a random state for CSRF protection
const state = crypto.getRandomValues(new Uint8Array(16))
  .reduce((s, b) => s + b.toString(16).padStart(2, '0'), '');

// 4. Store code_verifier and state before redirecting
sessionStorage.setItem('pkce_code_verifier', codeVerifier);
sessionStorage.setItem('oauth_state', state);
```

Required authorization request parameters:

- response_type=code
- client_id
- redirect_uri
- scope
- state
- code_challenge + code_challenge_method=S256 (PKCE)

##### Storage tip

Store the `code_verifier` and `state` in `sessionStorage` before redirecting — they survive the redirect and are automatically cleared when the tab is closed. Clear them from storage immediately after a successful token exchange.

## Step 2: Redirect the user to the authorization endpoint

Send users to Deriv's OAuth 2.0 authorization endpoint:

```bash
https://auth.deriv.com/oauth2/auth
```

### Login

Login uses the standard OAuth2 + PKCE parameters with no additions.

#### Parameters

| Parameter | Value | Description |
| --- | --- | --- |
| `response_type` Required | `code` | Request an authorization code |
| `client_id` Required | `Your app ID` | Registered OAuth2 application ID from Deriv |
| `redirect_uri` Required | `Your callback URL` | Must exactly match the URI registered with Deriv |
| `scope` Required | `trade account_manage` | Requested permissions |
| `state` Required | `Random string` | CSRF protection — generate a new value for each request |
| `code_challenge` Required | `BASE64URL(SHA256(verifier))` | The PKCE challenge derived from code_verifier |
| `code_challenge_method` Required | `S256` | Always SHA-256 |
| `app_id` Optional | `Your legacy app ID` | Your V1 app ID from the Legacy Deriv API — include this only if you also maintain a legacy API app |

#### Login URL

```bash
https://auth.deriv.com/oauth2/auth?
  response_type=code
  &client_id={YOUR_CLIENT_ID}          # e.g. app12345
  &redirect_uri={YOUR_REDIRECT_URI}    # e.g. https://yourapp.com/callback
  &scope=trade+account_manage
  &state={RANDOM_STATE}                # e.g. abc123random
  &code_challenge={PKCE_CHALLENGE}     # e.g. E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM
  &code_challenge_method=S256
```

##### Also maintaining a Legacy API app?

If you also have an app on the Legacy Deriv API, append `&app_id=YOUR_LEGACY_APP_ID` to the login URL (and sign up URL). Deriv will check whether the user belongs to the old or new platform and route them to the appropriate version of your app.

#### Login URL with legacy app support

```bash
https://auth.deriv.com/oauth2/auth?
  response_type=code
  &client_id={YOUR_CLIENT_ID}
  &redirect_uri={YOUR_REDIRECT_URI}
  &scope=trade+account_manage
  &state={RANDOM_STATE}
  &code_challenge={PKCE_CHALLENGE}
  &code_challenge_method=S256
  &app_id={YOUR_LEGACY_APP_ID}      # V1 app ID from legacy-api.deriv.com
```

### Sign Up

Sign up uses the same base URL and parameters as login, plus one additional required parameter:

#### Required sign up parameter

| Parameter | Value | Description |
| --- | --- | --- |
| `prompt` Required | `registration` | Always this exact value. Tells Deriv to show the signup form instead of login. |

#### Optional partner attribution parameters

The following parameters are all optional and managed in the Partners dashboard. Include them to attribute signups to your partner account. The tracking token parameter has four equivalent names ( `t` , `affiliate_token` , `sidi` , `ca` ) — use whichever one appears in your referral link or Partners dashboard.

| Parameter | Value | Purpose |
| --- | --- | --- |
| `t` `affiliate_token` `sidi` `ca` | Your affiliate tracking token | Tracking and attribution. Use **only one** of these parameter names — they are equivalent aliases. Pick the one that appears in your referral link or in the Partners dashboard. |
| `utm_campaign` | Your campaign name | Identifies the marketing campaign |
| `utm_medium` | affiliate | Indicates a partner integration |
| `utm_source` | Your affiliate ID | Commission tracking and reporting |

##### Which tracking parameter should I use?

`t` , `affiliate_token` , `sidi` , and `ca` all serve the same purpose. Use the one that appears in your Deriv referral link or in your Partners dashboard — don't include more than one.

#### Sign Up URL

```bash
https://auth.deriv.com/oauth2/auth?
  response_type=code
  &client_id={YOUR_CLIENT_ID}          # e.g. app12345
  &redirect_uri={YOUR_REDIRECT_URI}    # e.g. https://yourapp.com/callback
  &scope=trade+account_manage
  &state={RANDOM_STATE}                # e.g. abc123random
  &code_challenge={PKCE_CHALLENGE}     # e.g. E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM
  &code_challenge_method=S256
  &prompt=registration
  &t={YOUR_TRACKING_TOKEN}             # or: affiliate_token | sidi | ca — use the name from your referral link
  &utm_campaign={YOUR_CAMPAIGN}        # e.g. dynamicworks
  &utm_medium=affiliate
  &utm_source={YOUR_AFFILIATE_ID}      # e.g. CU303219
```

##### Important

Always validate the `state` parameter on return and generate your `code_challenge` from a secure random `code_verifier` . Never reuse these values between requests.

## Step 3: Handle the callback

Whether the user logged in or signed up, the callback works exactly the same way. After authentication, Deriv redirects to your `redirect_uri` :

```bash
https://yourapp.com/callback?code=AUTHORIZATION_CODE&state=RANDOM_STATE
```

If something went wrong:

```bash
https://yourapp.com/callback?error=access_denied&error_description=User+cancelled
```

### Your app must:

1. **Verify the state** — compare the `state` from the URL with the value you stored before the redirect. If they don't match, abort — it may be a CSRF attack.
2. **Extract the code** — read the `code` query parameter.

##### The authorization code is single-use and expires quickly

Exchange it immediately. Do not store or log authorization codes.

## Step 4: Exchange code for tokens

Make a POST request from your **backend** to the token endpoint. Never perform the token exchange from the browser.

```http
POST https://auth.deriv.com/oauth2/token
```

### Request body (form-encoded)

```bash
grant_type=authorization_code
client_id=YOUR_CLIENT_ID
code=AUTH_CODE_FROM_CALLBACK
code_verifier=YOUR_ORIGINAL_CODE_VERIFIER
redirect_uri=https://your-app.com/callback
```

### cURL example

```bash
curl -X POST https://auth.deriv.com/oauth2/token \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "grant_type=authorization_code" \
  -d "client_id=YOUR_CLIENT_ID" \
  -d "code=AUTH_CODE" \
  -d "code_verifier=YOUR_CODE_VERIFIER" \
  -d "redirect_uri=https://your-app.com/callback"
```

### Token response

```json
{
  "access_token": "ory_at_...",
  "expires_in": 3600,
  "token_type": "Bearer"
}
```

## Step 5: Use the access token in API calls

Include the access token as a Bearer token in the `Authorization` header for all API calls:

```http
Authorization: Bearer YOUR_ACCESS_TOKEN
```

### Example

```bash
curl -X GET "https://api.derivws.com/trading/v1/options/accounts" \
  -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
```

## Quick reference

| Endpoint | URL |
| --- | --- |
| Authorization | `https://auth.deriv.com/oauth2/auth` |
| Token exchange | `https://auth.deriv.com/oauth2/token` |
| API base URL | `https://api.derivws.com` |

Where to find your values:

| Value | Where |
| --- | --- |
| `client_id` | Register an OAuth2 app with Deriv — you'll receive an app ID |
| `redirect_uri` | Set during app registration — must match exactly |
| `t / affiliate_token / sidi / ca (signup)` | Your referral link or the Partners dashboard — use the exact parameter name shown there |
| `utm_source / affiliate ID (signup)` | Managed and set in the Partners dashboard |
| `utm_campaign (signup)` | Managed and set in the Partners dashboard |
| `app_id (legacy)` | Your V1 app ID from legacy-api.deriv.com — only needed if you maintain a Legacy API app |

## Troubleshooting

| Problem | Likely cause | Fix |
| --- | --- | --- |
| State mismatch error | state in the callback doesn't match stored value | Store state in sessionStorage before redirecting, and don't regenerate it on page load |
| invalid_grant on token exchange | code_verifier doesn't match the challenge, or code expired/already used | Send the original code_verifier, not a newly generated one; exchange the code immediately |
| Redirect URI mismatch | URL doesn't exactly match what's registered | Check for trailing slashes, http vs https, port numbers |
| invalid_client | Wrong client_id | Verify your credentials from the Deriv dashboard |
| Login form shows instead of signup | Missing prompt=registration | Add prompt=registration to the authorization URL |
| Signup not tracked to partner | Missing or wrong UTM parameters | Verify your tracking token parameter (one of t, affiliate_token, sidi, or ca) matches the one shown in your referral link, and that utm_source, utm_medium, and utm_campaign are all present and correct |

## Implementation checklist[Advanced](/docs)

# Complete Workflows

End-to-end examples of common trading workflows using the Deriv API

## Prerequisites

##### Important: Complete These Steps First

You must complete all prerequisites before making any API calls. Skipping these steps will result in `401 Unauthorized` errors.

1. **Log in to developers.deriv.com:** Create an account or log in with your credentials to access the dashboard.
2. **Register a new application:** Navigate to the Dashboard and register a new application under your account. Choose the appropriate application type based on your use case: - **PAT type:** Choose this when browser redirects are not practical and manual token entry is acceptable. For example, desktop tools, CLI apps, or native clients. The user generates a Personal Access Token in Deriv and pastes it into your app.
- **OAuth type:** Choose this when your product can handle browser redirects and you need a standard delegated flow with user authorisation. For example, web dashboards or browser apps. OAuth 2.0 issues short-lived tokens and minimises long-term credential sharing.

This will generate a new App ID. Your legacy App IDs will not work with the new APIs.
3. **Generate an authorization token:** - **If using PAT type:** In the Dashboard, go to the API tokens section. Create a new PAT (Personal Access Token) and select the appropriate scopes (e.g., `trade` , `account_manage` ). Copy and securely store your token. It cannot be viewed again after creation.
- **If using OAuth type:** You do not need to generate a token manually. Proceed to the OAuth 2.0 authentication flow described below. The flow will provide a short-lived access token after successful authentication. Ensure you have your `client_id` , `client_secret` , and an HTTPS `redirect_uri` registered.
4. **Configure your request headers:** Every REST API request must include both required headers:

```javascript
// Required headers for ALL REST API calls
headers: {
  'Authorization': 'Bearer pat_df0cbb0150b40589d016c49888fea3098f54ef3d5dde910f8e0ac4ef9f9fb0f5',  // Authorization token (PAT or JWT)
  'Deriv-App-ID': '33p7PVqGTbhzPMv1GNtXr',                      // App ID from your registered application
  'Content-Type': 'application/json'
}
```

##### Authorization Token

Throughout this documentation, "authorization token" refers to either your **PAT token** (Personal Access Token) or your **JWT token** (obtained via the OAuth 2.0 flow), depending on which authentication method you are using. Both token types work the same way: as a Bearer token in the `Authorization` header for REST API calls, and to obtain an authenticated WebSocket URL via the OTP endpoint.

## Options Trading Workflow (REST + WebSocket)

##### Complete Integration

Use REST APIs for account setup and the OTP endpoint to get an authenticated WebSocket URL for real-time trading.

1. **REST:** Get an authenticated WebSocket URL via the OTP endpoint (requires your authorization token)
2. **WebSocket:** Connect using the authenticated URL from the OTP response
3. **WebSocket:** Perform trading operations

**Note:** Users receive a default demo account upon signup. You do not need to create an account via the API before trading.

### Step 1: Get Authenticated WebSocket URL (REST)

This REST call requires your authorization token (PAT or JWT). The response contains an authenticated WebSocket URL that you can connect to directly. The URL determines whether you connect to a demo or real endpoint based on the account ID provided.

```javascript
// Get authenticated WebSocket URL via OTP endpoint
// Note: This REST call requires your authorization token
const otpResponse = await fetch(
  `https://api.derivws.com/trading/v1/options/accounts/${accountId}/otp`,
  {
    method: 'POST',
    headers: {
      'Authorization': 'Bearer pat_df0cbb0150b40589d016c49888fea3098f54ef3d5dde910f8e0ac4ef9f9fb0f5',  // PAT or JWT token
      'Deriv-App-ID': '33p7PVqGTbhzPMv1GNtXr'
    }
  }
);

const otpResult = await otpResponse.json();
const wsUrl = otpResult.data.url;
console.log('Authenticated WebSocket URL:', wsUrl);
// Output: wss://api.derivws.com/trading/v1/options/ws/demo?otp=abc123xyz789
```

### Step 2: Connect to WebSocket

**WebSocket Endpoints:** There are three WebSocket endpoints available: - **Public:** No authentication required. For market data and public information.
- **Demo:** Authenticated. For demo account trading.
- **Real:** Authenticated. For live account trading.

If the user is not logged in, use the public endpoint. Once authenticated, the OTP response URL will automatically point to the correct demo or real endpoint based on the account ID.

```javascript
// Connect to Options WebSocket using the authenticated URL from OTP response
// The URL already contains the correct endpoint (demo/real) and authentication
const ws = new WebSocket(wsUrl);

ws.onopen = () => {
  console.log('Connected to Options trading WebSocket');
  // Connection is now authenticated and ready for trading
};

ws.onmessage = (msg) => {
  const data = JSON.parse(msg.data);
  console.log('Received:', data);
};

ws.onerror = (error) => {
  console.error('WebSocket error:', error);
};

ws.onclose = () => {
  console.log('WebSocket connection closed');
};
```

### Step 3: Start Trading Operations

```javascript
// Once connected, you can send trading commands through WebSocket
// Example: Get account balance
ws.send(JSON.stringify({
  balance: 1,
  subscribe: 1,
  req_id: 1
}));

// Example: Subscribe to tick stream
ws.send(JSON.stringify({
  ticks: "1HZ100V",
  subscribe: 1,
  req_id: 2
}));

// Example: Get price proposal
ws.send(JSON.stringify({
  proposal: 1,
  amount: 10,
  basis: "stake",
  contract_type: "MULTDOWN",
  currency: "USD",
  duration_unit: "s",
  multiplier: 10,
  underlying_symbol: "1HZ100V",
  subscribe: 1,
  req_id: 3
}));
```

##### Complete Example

Complete example combining all steps:

```javascript
async function setupOptionsTrading() {
  const AUTH_TOKEN = 'pat_df0cbb0150b40589d016c49888fea3098f54ef3d5dde910f8e0ac4ef9f9fb0f5';  // PAT or JWT token
  const APP_ID = '33p7PVqGTbhzPMv1GNtXr';                   // App ID from registered application
  const API_BASE = 'https://api.derivws.com';
  const accountId = '019e4f44-45be-78e1-a2a7-808ded270fdd';            // Your demo or real account ID

  try {
    // Step 1: Get authenticated WebSocket URL (REST, requires authorization token)
    const otpResponse = await fetch(
      `${API_BASE}/trading/v1/options/accounts/${accountId}/otp`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${AUTH_TOKEN}`,
          'Deriv-App-ID': APP_ID
        }
      }
    );

    if (!otpResponse.ok) throw new Error(`HTTP error! status: ${otpResponse.status}`);
    const otpData = await otpResponse.json();
    const wsUrl = otpData.data.url;
    console.log('✓ Authenticated WebSocket URL obtained');

    // Step 2: Connect to WebSocket using the authenticated URL
    const ws = new WebSocket(wsUrl);

    ws.onopen = () => {
      console.log('✓ WebSocket connected');

      // Step 3: Start trading
      // Subscribe to balance updates
      ws.send(JSON.stringify({
        balance: 1,
        subscribe: 1,
        req_id: 1
      }));

      // Subscribe to ticks
      ws.send(JSON.stringify({
        ticks: "1HZ100V",
        subscribe: 1,
        req_id: 2
      }));
    };

    ws.onmessage = (msg) => {
      const data = JSON.parse(msg.data);

      if (data.msg_type === 'balance') {
        console.log('Balance:', data.balance.balance, data.balance.currency);
      }

      if (data.msg_type === 'tick') {
        console.log('Tick:', data.tick.quote);
      }
    };

    return ws;

  } catch (error) {
    console.error('Setup failed:', error);
    throw error;
  }
}

// Run the setup
setupOptionsTrading().then(ws => {
  console.log('Trading setup complete. WebSocket ready for operations.');
}).catch(err => {
  console.error('Failed to setup trading:', err);
});
```

## Authentication Workflows

### Workflow A: PAT-Based Authentication

With a PAT app, the user generates a Personal Access Token in Deriv and manually enters or pastes it into your application. The app securely stores the token and includes it in API requests as a bearer token. This is best suited for desktop tools, CLI apps, and native clients where browser redirects are not practical.

1. Log in to `developers.deriv.com` with your credentials
2. Register a new application with **PAT type** in the Dashboard
3. Generate a PAT token with appropriate scopes
4. Include `Authorization: Bearer <YOUR_AUTHORIZATION_TOKEN>` and `Deriv-App-ID` in all REST request headers
5. Make authenticated REST API calls

```javascript
// PAT-Based Authentication: REST API
const AUTH_TOKEN = 'pat_df0cbb0150b40589d016c49888fea3098f54ef3d5dde910f8e0ac4ef9f9fb0f5';  // Your PAT token
const APP_ID = '33p7PVqGTbhzPMv1GNtXr';

// All REST calls use the authorization token as a Bearer token
const response = await fetch('https://api.derivws.com/trading/v1/options/accounts', {
  method: 'POST',
  headers: {
    'Authorization': `Bearer ${pat_df0cbb0150b40589d016c49888fea3098f54ef3d5dde910f8e0ac4ef9f9fb0f5}`,    // Authorization token (PAT)
    'Deriv-App-ID': 33p7PVqGTbhzPMv1GNtXr,                      // App ID from registered application
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    currency: 'USD',
    group: 'row',
    account_type: 'demo'
  })
});

const result = await response.json();
console.log('Authenticated REST call successful:', result);
```

### Workflow B: OAuth 2.0 Authentication

OAuth 2.0 lets users grant your app access without sharing their password. Your app redirects the user to a Deriv sign-in and consent page. After the user logs in and approves permissions, Deriv returns an authorization code to your app. You exchange this code for an access token, which you then use to authenticate API requests. Recommended for web-based applications onboarding end users.

#### Before You Begin

- Ensure your redirect URL is correctly registered in the dashboard
- The redirect URL must use HTTPS
- Your app must handle redirects, read the authorization code, and exchange it for tokens
- You must have a registered OAuth 2.0 client with valid credentials: `client_id` , `client_secret` , and `redirect_uri`
- All redirect URLs (including subdirectories) must be whitelisted. URLs must match exactly.

##### Important: Redirect URL Whitelisting

When registering your OAuth application, you must define all redirect URLs in the dashboard. If you have given a URL like `https://abc.com` but your redirect URL is `https://abc.com/callback` , the flow will fail. Every subdirectory must be registered separately.

#### OAuth 2.0 Flow Steps

1. Your app redirects the user to Deriv's OAuth 2.0 authorization page to sign in and review permissions
2. The authorization server handles login and consent securely
3. After login, Deriv redirects the user back to your app with an **authorization code** and **state** parameter
4. Your app exchanges this code for tokens (with PKCE if used)
5. The OAuth server returns the **access token** (and optional refresh token)
6. Your app securely stores and uses the access token for WebSocket or REST API calls

```javascript
// OAuth 2.0 Authentication Flow (Authorization Code with PKCE)
const CLIENT_ID = '019e4f44-45be-78e1-a2a7-808ded270fdd';
const REDIRECT_URI = 'https://alphones142775-cmyk.github.io/Trading-platform/';

// --- PKCE Helper Functions ---
function generateCodeVerifier() {
  const array = new Uint8Array(32);
  crypto.getRandomValues(array);
  return btoa(String.fromCharCode(...array))
    .replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

async function generateCodeChallenge(verifier) {
  const encoder = new TextEncoder();
  const data = encoder.encode(verifier);
  const digest = await crypto.subtle.digest('SHA-256', data);
  return btoa(String.fromCharCode(...new Uint8Array(digest)))
    .replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

// Step 1: Generate PKCE values and redirect user to authorization endpoint
const codeVerifier = generateCodeVerifier();
const codeChallenge = await generateCodeChallenge(codeVerifier);
const state = crypto.randomUUID();

sessionStorage.setItem('code_verifier', codeVerifier);
sessionStorage.setItem('oauth_state', state);

const authUrl = new URL('https://auth.deriv.com/oauth2/auth');
authUrl.searchParams.set('response_type', 'code');
authUrl.searchParams.set('client_id', 019e4f44-45be-78e1-a2a7-808ded270fdd);
authUrl.searchParams.set('redirect_uri', https://alphones142775-cmyk.github.io/Trading-platform/);
authUrl.searchParams.set('scope', 'trade account_manage');
authUrl.searchParams.set('state', state);
authUrl.searchParams.set('code_challenge', codeChallenge);
authUrl.searchParams.set('code_challenge_method', 'S256');

window.location.href = authUrl.toString();

// Step 3: Handle the callback
const urlParams = new URLSearchParams(window.location.search);
const authorizationCode = urlParams.get('code');
const returnedState = urlParams.get('state');

const savedState = sessionStorage.getItem('oauth_state');
if (returnedState !== savedState) {
  throw new Error('State mismatch: possible CSRF attack');
}

// Step 4: Exchange the authorization code for tokens
const savedVerifier = sessionStorage.getItem('code_verifier');
const tokenResponse = await fetch('https://auth.deriv.com/oauth2/token', {
  method: 'POST',
  headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  body: new URLSearchParams({
    grant_type: 'pat_df0cbb0150b40589d016c49888fea3098f54ef3d5dde910f8e0ac4ef9f9fb0f5',
    client_id: 019e4f44-45be-78e1-a2a7-808ded270fdd,
    code: authorizationCode,
    redirect_uri: https://alphones142775-cmyk.github.io/Trading-platform/,
    code_verifier: savedVerifier
  })
});

const tokenData = await tokenResponse.json();
const accessToken = tokenData.access_token;
console.log('Access token obtained, expires in', tokenData.expires_in, 'seconds');

// Step 6: Use the access token for authenticated API calls
const response = await fetch('https://api.derivws.com/trading/v1/options/accounts', {
  method: 'GET',
  headers: {
    'Authorization': `pat_df0cbb0150b40589d016c49888fea3098f54ef3d5dde910f8e0ac4ef9f9fb0f5}`,
    'Deriv-App-ID': 33p7PVqGTbhzPMv1GNtXr,
    'Content-Type': 'application/json'
  }
});

const result = await response.json();
console.log('Authenticated API call successful:', result);
```

##### Security Best Practices

- Always validate the `state` parameter to prevent CSRF attacks
- Generate your `code_challenge` from a cryptographically secure random `code_verifier`
- Store tokens securely on the server. Never expose them in frontend code.
- Access tokens are short-lived (typically 3600 seconds) and must be refreshed
- The authorization code is single-use and short-lived

### WebSocket Authentication (OTP)

To connect to an authenticated WebSocket endpoint, you need to call the OTP REST endpoint using your authorization token (PAT or JWT). The response contains an authenticated WebSocket URL that you can connect to directly. The URL handles the authentication for you.

#### WebSocket Endpoints:

Public

No authentication required

Use for market data and public information. No login needed.

Demo

Authenticated

Use for demo/virtual account trading operations. The OTP response URL will point to this endpoint for demo accounts.

Real

Authenticated

Use for live/real account trading. The OTP response URL will point to this endpoint for real accounts.

```javascript
// Step 1: Get authenticated WebSocket URL via REST (requires authorization token)
const otpResponse = await fetch(
  `https://api.derivws.com/trading/v1/options/accounts/${accountId}/otp`,
  {
    method: 'POST',
    headers: {
      'Authorization': 'pat_df0cbb0150b40589d016c49888fea3098f54ef3d5dde910f8e0ac4ef9f9fb0f5',  // PAT or JWT token
      'Deriv-App-ID': '33p7PVqGTbhzPMv1GNtXr'
    }
  }
);

const otpResult = await otpResponse.json();
const wsUrl = otpResult.data.url;
// The URL already includes the correct endpoint and authentication
// Output: wss://api.derivws.com/trading/v1/options/ws/demo?otp=abc123xyz789

// Step 2: Connect to WebSocket using the authenticated URL
const ws = new WebSocket(wsUrl);

ws.onopen = () => {
  console.log('WebSocket authenticated and connected');
  // Ready for trading operations
};
```

## Complete Trading Workflow

##### End-to-End Trading Process

This workflow shows how to authenticate, get market data, create a proposal, buy a contract, and monitor it.

1. Establish connection and authenticate
2. Get active symbols using `active_symbols`
3. Subscribe to tick stream for chosen symbol using `ticks`
4. Get contract proposal using `proposal` (with subscribe)
5. Monitor real-time price updates
6. When ready, buy contract using `buy`
7. Subscribe to contract updates using `proposal_open_contract`
8. Monitor contract status in real-time
9. Optionally sell early using `sell`
10. Check portfolio using `portfolio`

```javascript
// After authentication...

// 1. Get active symbols
ws.send(JSON.stringify({
  active_symbols: "brief",
  req_id: 3
}));

// 2. Subscribe to ticks
ws.send(JSON.stringify({
  ticks: "1HZ100V",
  subscribe: 1,
  req_id: 4
}));

// 3. Get price proposal
ws.send(JSON.stringify({
  proposal: 1,
  amount: 10,
  basis: "stake",
  contract_type: "MULTDOWN",
  currency: "USD",
  duration_unit: "s",
  multiplier: 10,
  underlying_symbol: "1HZ100V",
  subscribe: 1,
  req_id: 5
}));

// 4. Buy the contract (when ready)
// Use proposal ID from previous response
ws.send(JSON.stringify({
  buy: "PROPOSAL_ID_HERE",
  price: 100,
  req_id: 6
}));

// 5. Monitor contract status
ws.send(JSON.stringify({
  proposal_open_contract: 1,
  contract_id: CONTRACT_ID,
  subscribe: 1,
  req_id: 7
}));
```

## Market Data Workflow

##### No Authentication Required

You can access market data using the **public** WebSocket endpoint without authentication. Perfect for building chart applications or market monitors.

1. Connect to the public WebSocket endpoint (no auth needed)
2. Request `active_symbols` to see available markets
3. Subscribe to `ticks` for real-time price updates
4. Optionally get `ticks_history` for historical data
5. Use `contracts_for` to see available contract types
6. Stream continues until `forget` or disconnect

```javascript
// Connect to the public WebSocket endpoint (no authentication required)
const ws = new WebSocket('wss://ws.binaryws.com/websockets/v3');

ws.onopen = () => {
  // Get available symbols
  ws.send(JSON.stringify({
    active_symbols: "brief",
    product_type: "basic",
    req_id: 1
  }));

  // Subscribe to tick stream
  ws.send(JSON.stringify({
    ticks: "1HZ100V",
    subscribe: 1,
    req_id: 2
  }));

  // Get historical data
  ws.send(JSON.stringify({
    ticks_history: "1HZ100V",
    count: 100,
    end: "latest",
    style: "ticks",
    req_id: 3
  }));
};

ws.onmessage = ([Getting Started](/docs)

# OAuth 2.0

A complete guide to implementing Login and Sign Up using Deriv's OAuth 2.0 Authorization Code flow with PKCE.

## How the flow works

1

Generate PKCE

2

Redirect to Deriv

3

User Authenticates

4

Exchange Code

5

Use Token

1. **Generate PKCE** — Create a `code_verifier` (random string) and derive `code_challenge` = BASE64URL(SHA256(code_verifier)). Also generate a random `state` for CSRF protection.
2. **Redirect to Deriv** — Send the user to Deriv's authorization URL with all required parameters.
3. **User authenticates** — Deriv shows either the login or registration form. All login and consent screens are managed by the OAuth provider.
4. **Redirect back** — Deriv redirects the user to your `redirect_uri` with an authorization `code` and `state` .
5. **Verify state** — Confirm the returned `state` matches what you stored. This prevents CSRF attacks.
6. **Exchange code for token** — Your backend sends the `code` + `code_verifier` to Deriv's token endpoint and receives an `access_token` .
7. **Use the token** — Make authenticated API calls using the Bearer token.

## Before you start

You need:

- A registered OAuth2 client from Deriv with a `client_id` and a pre-registered `redirect_uri` .
- HTTPS enabled on your redirect URL.
- Your app must handle redirects, read the authorization code, and exchange it for tokens.

## Step 1: Generate PKCE parameters

##### What is PKCE?

**PKCE** (Proof Key for Code Exchange, pronounced “pixy”) prevents authorization code interception attacks. Even if an attacker intercepts the authorization code, they cannot exchange it without the original `code_verifier` that only your app generated and stored.

| Term | What it is |
| --- | --- |
| `code_verifier` | A cryptographically random string (43–128 characters) generated by your app |
| `code_challenge` | `BASE64URL(SHA256(code_verifier))` — sent with the authorization request |
| `code_challenge_method` | Always S256 (SHA-256) |

**Why it works:** Only the app that generated the `code_verifier` can complete the token exchange.

### Generating PKCE in JavaScript

```javascript
// 1. Generate a random code_verifier
const array = crypto.getRandomValues(new Uint8Array(64));
const codeVerifier = Array.from(array)
  .map(v => 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~'[v % 66])
  .join('');

// 2. Derive the code_challenge
const hash = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(codeVerifier));
const codeChallenge = btoa(String.fromCharCode(...new Uint8Array(hash)))
  .replace(/\+/g, '-')
  .replace(/\//g, '_')
  .replace(/=+$/, '');

// 3. Generate a random state for CSRF protection
const state = crypto.getRandomValues(new Uint8Array(16))
  .reduce((s, b) => s + b.toString(16).padStart(2, '0'), '');

// 4. Store code_verifier and state before redirecting
sessionStorage.setItem('pkce_code_verifier', codeVerifier);
sessionStorage.setItem('oauth_state', state);
```

Required authorization request parameters:

- response_type=code
- client_id
- redirect_uri
- scope
- state
- code_challenge + code_challenge_method=S256 (PKCE)

##### Storage tip

Store the `code_verifier` and `state` in `sessionStorage` before redirecting — they survive the redirect and are automatically cleared when the tab is closed. Clear them from storage immediately after a successful token exchange.

## Step 2: Redirect the user to the authorization endpoint

Send users to Deriv's OAuth 2.0 authorization endpoint:

```bash
https://auth.deriv.com/oauth2/


  let lastPrice = null;
  let time = Math.floor(Date.now() / 1000);


  connection.onmessage = (event) => {

    const data = JSON.parse(event.data);

    if(data.tick){

      const price = parseFloat(data.tick.quote);

      document.getElementById("balance").innerText = "$10,000";

      if(lastPrice === null){
        lastPrice = price;
      }

      candleSeries.update({
        time: time++,
        open: lastPrice,
        high: Math.max(lastPrice, price),
        low: Math.min(lastPrice, price),
        close: price
      });

      lastPrice = price;
    }
  };
}
